version: '3.8'
services:
  patient-services:
    image: patient-services:latest
    build:
      context: .
      dockerfile: Patient-Services/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mysql_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql_db;Database=PatientDB;User=root;Password=Jemeconnecte24!;
 
  medicalnotes-service:
    image: medicalnotes-service:latest
    build:
      context: .
      dockerfile: MediacalNotes-Service/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - mongo_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://root:example@mongo_db:27017/
      - MongoDbSettings__DatabaseName=Notes
 
  diabetes-risk-assessment:
    image: diabetes-risk-assessment:latest
    build:
      context: .
      dockerfile: DiabetesRiskAssessmentService/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - mongo_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://root:example@mongo_db:27017/
      - MongoDbSettings__DatabaseName=diabetesdb
 
  api-gateway:
    image: api-gateway:latest
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - patient-services
      - medicalnotes-service
      - diabetes-risk-assessment
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
 
  microfrontend:
    image: microfrontend:latest
    build:
      context: .
      dockerfile: MicroFrontEnd/Dockerfile
    ports:
      - "5004:80"
    depends_on:
      - api-gateway
 
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Jemeconnecte24!
      MYSQL_DATABASE: PatientDB
    volumes:
      - mysql_data:/var/lib/mysql
 
  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
 
networks:
  default:
    external:
      name: my_network
 
volumes:
  mysql_data:
  mongo_data: